### ISSUE TITLE
[ARCHIVE] Bug Fixes

### ISSUE THREAD

**Issue by MagLjudik** [FullFrontalFrog/OhSoHeroTracker#113]
### Description
Originally created: 2023-12-28T13:50:54.474Z

Due: 

### Tasks

- [x] enable Joe' slide hitbox/hurtbox sooner
- [x] enemy AI will only use grab moves if Joe is swooned
- [x] fix some enemy AI issues and enemy attack hitboxes
- [x] prevent game crash if loading corrupt save file
- [x] save stats to save file; max HP on load
- [x] fix softlock at 0 HP if pressing X while in climax state
- [x] fix respawning after falling in water
- [x] no damage during forest sexy switch animation
- [x] fix all control prompts to use active input method
- [x] some dialogue-related tweaks and fixes
- [x] reduce spring sound effect volume
- [x] wood crate fragments will not interact with springs
- [x] fix bug upon opening/closing credits screen multiple times
- [x] and more!
